//
// pong.js — Tournament-aware + Casual Mode
//

// -------------------------------------------------
// SOCKET.IO INIT
// -------------------------------------------------
const socket = io("/", {
  path: "/socket.io",
  transports: ["websocket"]
});

// -------------------------------------------------
// CANVAS + ELEMENTS
// -------------------------------------------------
const canvas = document.getElementById("gameCanvas");
const ctx = canvas.getContext("2d");
const statusBox = document.getElementById("status");
const controls = document.getElementById("controls");

// -------------------------------------------------
// QUERY PARAMS FOR TOURNAMENT MODE
// URL example:
//   pong.html?match=t3-r1-m0&tid=3&tmid=7&alias=Rex&opponent=Bob
// -------------------------------------------------
const params = new URLSearchParams(window.location.search);

// matchId used by Pong rooms → always pong_match_id (string)
const matchId = params.get("match");    

// tournamentId (number)
const tournamentId = params.get("tid") ? Number(params.get("tid")) : null;

// tournamentMatchId (number, for DB)
const tournamentMatchId = params.get("tmid")
  ? Number(params.get("tmid"))
  : null;

// aliases (optional but nice)
const yourAlias = params.get("alias") || "You";
const opponentAlias = params.get("opponent") || "Opponent";

// Tournament mode is active if matchId + tournamentId exist
const isTournament = !!(matchId && tournamentId);

// -------------------------------------------------
// CASUAL MODE BUTTONS
// -------------------------------------------------
const btnAI = document.getElementById("btn_ai");
const btnHuman = document.getElementById("btn_human");

if (btnAI) {
  btnAI.onclick = () => {
    socket.emit("join_casual", { vsAi: true, difficulty: "medium" });
  };
}

if (btnHuman) {
  btnHuman.onclick = () => {
    socket.emit("join_casual", { vsAi: false });
  };
}

// -------------------------------------------------
// ON CONNECT → AUTO-JOIN TOURNAMENT
// -------------------------------------------------
socket.on("connect", () => {
  if (isTournament) {
    // Hide casual-mode buttons
    if (controls) controls.style.display = "none";

    statusBox.innerHTML = `
      Joining tournament match...<br>
      Match Key: ${matchId}<br>
      ${yourAlias} vs ${opponentAlias}
    `;

    // "matchId" MUST equal pong_match_id generated by the user-service
    socket.emit("join_match", {
      matchId: matchId,
      tournamentId: tournamentId,
      tournamentMatchId: tournamentMatchId
    });
  } else {
    // Pure casual mode
    if (controls) controls.style.display = "block";
    statusBox.innerHTML = "Select a mode: Human vs Human or vs AI.";
  }
});

// -------------------------------------------------
// RENDER FUNCTION
// -------------------------------------------------
function draw(state) {
  ctx.clearRect(0, 0, canvas.width, canvas.height);

  // === Background ===
  ctx.fillStyle = "black";
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  // === Ball ===
  ctx.fillStyle = "white";
  ctx.beginPath();
  ctx.arc(state.ball.position.x, state.ball.position.y, 8, 0, Math.PI * 2);
  ctx.fill();

  // === Paddles ===
  ctx.fillRect(20, state.paddles.left.y, 10, state.paddles.left.height);
  ctx.fillRect(
    canvas.width - 30,
    state.paddles.right.y,
    10,
    state.paddles.right.height
  );

  // === Score ===
  ctx.font = "26px Arial";
  ctx.fillText(state.score.left, canvas.width / 2 - 50, 40);
  ctx.fillText(state.score.right, canvas.width / 2 + 30, 40);
}

// -------------------------------------------------
// GAME STATE FROM SERVER
// -------------------------------------------------
socket.on("state", (state) => {
  draw(state);

  if (isTournament) {
    statusBox.innerHTML = `
      🏆 Tournament Match #${tournamentId}<br>
      ${yourAlias} vs ${opponentAlias}<br>
      Score: ${state.score.left} - ${state.score.right}
    `;
  }
});

// -------------------------------------------------
// MATCH START
// -------------------------------------------------
socket.on("match_start", (info) => {
  statusBox.innerHTML = `
    Match Started<br>
    Mode: ${info.mode}<br>
    Opponent: ${info.opponent}
  `;
});

// -------------------------------------------------
// MATCH END
// -------------------------------------------------
socket.on("match_end", (end) => {
  statusBox.innerHTML = `
    Match Ended<br>
    Winner: ${end.winnerSide.toUpperCase()}<br>
    Score: ${end.score.left} - ${end.score.right}
  `;

  // Tournament → return to lobby after 4 seconds
  if (end.tournamentId) {
    setTimeout(() => {
      window.location.href = `/tournament.html`;
    }, 4000);
  }
});

// -------------------------------------------------
// KEYBOARD INPUT
// -------------------------------------------------
document.addEventListener("keydown", (e) => {
  if (e.key === "ArrowUp") socket.emit("input", { up: true });
  if (e.key === "ArrowDown") socket.emit("input", { down: true });
});

document.addEventListener("keyup", (e) => {
  if (e.key === "ArrowUp") socket.emit("input", { up: false });
  if (e.key === "ArrowDown") socket.emit("input", { down: false });
});
